src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    const STATUS_NEW       = 0;
    const STATUS_ACTIVE    = 1;
    const STATUS_COMPLETED = 2;

    const STATUS_LIST = [
        self::STATUS_NEW       => 'New',
        self::STATUS_ACTIVE    => 'Active',
        self::STATUS_COMPLETED => 'Completed',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $description;

    /**
     * @var integer
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $status;

    /**
     * @var User
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $author;

    /**
     * @var User
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="tasks")
     * @ORM\JoinTable(name="user_tasks")
     */
    private $executors;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="task", cascade={"remove"})
     */
    private $comments;

    /**
     * Task constructor.
     * @param $id
     */
    public function __construct()
    {
        $this->status = self::STATUS_NEW;
        $this->comments = new ArrayCollection();
        $this->executors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function getStatusName(): string
    {
        return self::STATUS_LIST[$this->getStatus()] ?? '';
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getExecutors(): Collection
    {
        return $this->executors;
    }

    public function clearExecutors()
    {
        $this->executors = new ArrayCollection();

        return $this;
    }

    public function addExecutor(User $executor): self
    {
        if (!is_null($executor) && !$this->executors->contains($executor)) {
            $this->executors[] = $executor;
        }

        return $this;
    }

    public function removeExecutor(User $executor): self
    {
        if ($this->executors->contains($executor)) {
            $this->executors->removeElement($executor);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTask($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTask() === $this) {
                $comment->setTask(null);
            }
        }

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\User;
use App\Validator\UniqueExecutors;
use Doctrine\DBAL\Types\ArrayType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', TextareaType::class)
            ->add('status', ChoiceType::class, [
                'choices' => array_flip(Task::STATUS_LIST)
            ])
            ->add('executors', CollectionType::class, [
                'entry_type'   => UserType::class,
                'allow_add'    => true,
                'allow_delete' => true,
                'label'        => false,
                'constraints'  => [
                    new UniqueExecutors()
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Task;
use App\Form\CommentType;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/task")
 * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
 */
class TaskController extends AbstractController
{
    /**
     * @Route("/", name="task_index", methods="GET")
     * @param TaskRepository $taskRepository
     * @return Response
     */
    public function index(TaskRepository $taskRepository): Response
    {
        $tasks = $this->get('doctrine')->getRepository(Task::class)->getTasksWithMaxCommentData();

        return $this->render('task/index.html.twig', ['tasks' => $tasks]);
    }

    /**
     * @Route("/new", name="task_new", methods="GET|POST")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($task);
            $em->flush();

            return $this->redirectToRoute('task_index');
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_show", methods="GET")
     * @param Task $task
     * @return Response
     */
    public function show(Task $task): Response
    {
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment, [
                'action' => $this->generateUrl('comment_new', ['id' => $task->getId()])
            ]
        );

        return $this->render('task/show.html.twig', [
            'task'     => $task,
            'comment'  => $comment,
            'comments' => $task->getComments(),
            'form'     => $commentForm->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="task_edit", methods="GET|POST")
     * @param Request $request
     * @param Task $task
     * @return Response
     */
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('task_edit', ['id' => $task->getId()]);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_delete", methods="DELETE")
     * @param Request $request
     * @param Task $task
     * @return Response
     */
    public function delete(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($task);
            $em->flush();
        }

        return $this->redirectToRoute('task_index');
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/_form.html.twig
{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            updateDeleteButtons();

            $('#add').click(function(e) {
                e.preventDefault();

                var list = $('#task_executors');
                var newWidget = list.attr('data-prototype');
                console.log(newWidget);
                newWidget = newWidget.replace(/__name__label__/g, '');
                newWidget = newWidget.replace(/__name__/g, 1);

                list.append(newWidget);
                updateExecutorsIndex();
                updateDeleteButtons();

            });

            $('body').on("click", '.delete-btn', function (e) {
                e.preventDefault();
                $(this).parent('div').remove();

                updateExecutorsIndex();

            });
        });

        function updateExecutorsIndex() {
            $("select[name^='task[executors][']").each(function (index) {
                $(this).attr('name', 'task[executors][' + index + ']');
            });
        }

        function updateDeleteButtons() {
            $("select[name^='task[executors][']").each(function () {
                console.log($(this).parent("div").find('.delete-btn').length);
                if($(this).parent("div").find('.delete-btn').length === 0){

                $("<button class='delete-btn'>DELETE</button>").insertAfter($(this));
                }
            });
        }

    </script>

{% endblock %}


{{ form_start(form) }}
{{ form_errors(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.status) }}
    {{ form_row(form.executors) }}


<button id="add">ADD</button>

<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('task_index') }}">back to list</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <h1>Tasks</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Author</th>
                <th>Comment length</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.name|noData }}</td>
                <td> {{ task.email|noData }} </td>
                <td>{{ task.commentLength|noData }}</td>
                <td>
                    <a href="{{ path('task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>
                    {{ include('task/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('task_new') }}">Create new</a>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <h1>Create new Task</h1>

    {{ include('task/_form.html.twig') }}

    <a href="{{ path('task_index') }}">back to list</a>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ task.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ task.name }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ task.description }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ task.statusName }}</td>
        </tr>
        <tr>
            <th>Author</th>
            <td>{{ task.author.username }}</td>
        </tr>
        <tr>
            <th>Executors</th>
            <td>
                <ul>
                {% for executor in task.executors %}
                    <li>{{ executor.username }} ({{ executor.email }}) </li>
                {% endfor %}
                </ul>
            </td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('task_index') }}">back to list</a>

    <a href="{{ path('task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}

    {{ include('comment/index.html.twig') }}

    {{ include('comment/new.html.twig') }}

{% endblock %}